### ISSUE TITLE
Remove NUnit from Nuget

### ISSUE THREAD

**Issue by chrismckelt** [louisukiri/SlackClient#3]
Hi

Is it possible to remove the NUnit reference from the Nuget solution?

When I pull this down into a core solution - it pulls down the reference to NUnit.

Thanks

**Comment by louisukiri** [comment]
Sorry I am just getting to this. I'll put out a fix for this momentarily

**Comment by louisukiri** [comment]
Fix has been released into version 0.5.0

**Comment by chrismckelt** [comment]
:+1:
